# Generated by Django 5.0.4 on 2024-05-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ims", "0003_course_author_lesson_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="url",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Ссылка на видеоурок",
            ),
        ),
    ]
