# Generated by Django 5.0.4 on 2024-05-27 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ims", "0006_subscription_subscription_is"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="subscription_is",
        ),
    ]
