# Generated by Django 5.0.4 on 2024-06-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("Наличные", "cash"), ("Перевод на счёт", "card")],
                default="cash",
                max_length=100,
                verbose_name="способ оплаты",
            ),
        ),
    ]
