# Generated by Django 5.0.4 on 2024-06-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="Cсылка на оплату"
            ),
        ),
    ]
