# Generated by Django 5.0.4 on 2024-06-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payment_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_sum",
            field=models.PositiveIntegerField(default=100, verbose_name="сумма оплаты"),
        ),
    ]
