# Generated by Django 5.0.4 on 2024-06-02 10:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_payment_payment_sum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="дата"
            ),
        ),
    ]
